spring:
  application:
    name: boot-jwt-auth-server

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jwt_auth
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    user:
      name: user
      password: 1234

logging:
  level:
    me.hwanse: info