spring:
  application:
    name: jwt-auth-server

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jwt_auth
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    me.hwanse: info

jwt:
  token:
    header: Authorization
    issuer: ${spring.application.name}
    secret: aHdhbnNlLXNwcmluZy1zZWN1cml0eS1qd3QtYXV0aC1zZXJ2ZXItc2VjcmV0LWtleQo=
    expiration: 3600